pkg install nodejs
python gensim-3.8.3/setup.py install
npm i nodemon
npm i i18next-xhr-backend
npm i react-i18next
npm i i18next-http-backend
npm install uniqid
pip install pickle
pip install bz2
pip install pickle
pip install nltk
pip install re
pip install urllib
pip install codecs
pip install multiprocessing
pip install psycopg2-binary
pip install codecs
pip install numpy
pip install json
pip install scipy
pip install sklearn