npm i nodemon
npm i i18next-xhr-backend
npm i react-i18next
npm i i18next-http-backend
npm install uniqid
pip install pickle-mixin
pip install bz2file
pip install nltk
pip install regex
pip install multiprocess
pip install psycopg2-binary
pip install codecs
pip install numpy
pip install scipy
pip install scikit-learn
pip install gensim==3.8.3